### ISSUE TITLE
Anti-Tampering with Google App Signing

### ISSUE THREAD

**Issue by RayanArnaout** [preemptive/dasho-samples#2]
Hello,

How can we ensure the app is not being tampered if we do not have access to the final JKS used to sign the app by google when pushing it to the play store ?  [Google App Signing](https://support.google.com/googleplay/android-developer/answer/7384423?hl=en#)
I'm refering to this line in the project.dox file : 
`<signerInfo alias="correct_cert" storepass="[SbJlvHrFg8s4GblvgMcQ4w==]" keystore="keystore.ks"/>`

Thanks !
Rayan

**Comment by truist** [comment]
Rayan,

We are aware of this issue and there is a way to make it work, but it depends on a minor change that we have to make to DashO. We have the change queued up for our next release (DashO v9.0), which should be out in a few weeks. The release will include documentation for how to do it, as well.

If you have further questions, please [submit a support request](https://www.preemptive.com/contact/supportrequestform) and we'll be able to talk it through with you. 

In the meantime, I'll leave this ticket open until v9.0 is out.

Thanks,
Nathan

**Comment by truist** [comment]
Rayan,

If you download [DashO 9.0](https://www.preemptive.com/support/dasho-support/dasho-change-log/1000) you should be able to follow the [new instructions for using Tamper Check with Google Play App Signing](https://www.preemptive.com/dasho/pro/userguide/en/checks_tamperCheck.html#google_play_signing).

Nathan
