### ISSUE TITLE
Debugging enabled when building release

### ISSUE THREAD

**Issue by RayanArnaout** [preemptive/dasho-samples#3]
Hello,

I downloaded the latest release (9.2.0) and launched the "DebuggingOnAndroid" project (using DashO 9.2.0). I built the release version but I get "This app has debugging enabled." when opening the Random Generator.
 
Just to be sure, I tested the 9.0.0 sample project (9.1.0 would not compile...) and when building the release version (using DashO 9.0.0 or 9.1.0), I get the right toast "This app does not have debugging enabled.". But if I build the same release version using DashO 9.2.0, I get the "This app has debugging enabled." toast.

Is this normal ?

Thanks,
Rayan

**Comment by minsko** [comment]
It is most likely the "USB debugging" setting as mentioned in  README.md:

> Note: If USB debugging is enabled, then the DebugEnabledCheck will trigger. USB debugging is required to deploy the application to a real device, and some emulators have USB debugging enabled by default. Disable USB debugging in Developer options before running the application if it is enabled.

Please double-check that you do not have "USB debugging" enabled on the device where the sample is installed.
